# Copyright (C) 2018 FALLET Nathan
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Plugin Replica by ZabriCraft

# Nombre de parties à charger
# Number of games to load
games-amount: 1

# Choix du delay avant le debut de la partie
# Delay before start the game
countdown: 30

# Commande execute par le joueur pour retourner au spawn
# Command executed by the player to return to the spawn
spawn-command: 'spawn'

# Commandes de recompenses
# Reward commands
# Utilisez %player% comme le pseudo du joueur
# Use %player% like the player nickname
reward-commands:
- 'give %player% diamond 1'

# Images du jeu
# Pictures of the game
# Utilisez ReplicaPictureMaker.jar (disponible sur le site www.zabricraft.fr) pour créer les images
# Use ReplicaPictureMaker.jar (available on www.zabricraft.fr) to create the pictures
pictures:
  unrond:
    name: 'Un rond'
    blocks: '8;8;14;14;14;14;8;8;8;14;14;13;13;14;14;8;14;14;13;5;5;13;14;14;14;13;5;10;10;5;13;14;14;13;5;10;10;5;13;14;14;14;13;5;5;13;14;14;8;14;14;13;13;14;14;8;8;8;14;14;14;14;8;8'
  unrectangle:
    name: 'Un rectangle'
    blocks: '3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;15;15;15;15;15;15;15;15;15;14;4;7;7;4;14;15;15;14;4;7;7;4;14;15;15;15;15;15;15;15;15;15;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3'